### ISSUE TITLE
Support more FileSystems 

### ISSUE THREAD

**Issue by Dexus** [leonelquinteros/gotext#17]
# Please describe your issue

## Is this a bug, an improvement, a proposal or something else? 

- [x] Improvement

## Briefly explain your issue

Support more FileSystems like VFS, go-bindata, fileb0x etc.

## What's the expected behaviour? 

Creation of an abstraction of file systems to be used. So that it is possible to use not only the system file system but also other virtual file systems.

## What's the actual behaviour?

Only supported the system file systems.

## Comments

It should be possible to have an embedded filesystem, so that it is possible to have a binary only application. Without having to pass the locale to an external directory for each instance.

**Comment by Dexus** [comment]
As already written in #18, I will push something for the next days, then maybe it will be a bit clearer and we will be able to install something like that. We work with a singleton so that we can process everything in one place and our application can work with it.

Maybe it's not elegant, but you can form your own opinion in a few days and maybe you can work with it.

Greetings, Josef

**Comment by leonelquinteros** [comment]
Having the option to load a Po file from any source, and now, the option to implement external Translator objects that can work with other translation sources, I'll leave this feature to be implemented by any third party or package users when convenient. 

Not going to include this feature in the package.
