### ISSUE TITLE
Add support for MO files

### ISSUE THREAD

**Issue by leonelquinteros** [leonelquinteros/gotext#2]
Create a parsing method to work with MO file formats.

**Comment by ptman** [comment]
There's some ideas about MO parsing in https://github.com/giefferre/gettext/blob/master/mo.go (or https://github.com/gorilla/i18n/blob/master/gettext/mo.go )

**Comment by Dexus** [comment]
This will be the next when you like to accept #16.

**Comment by leonelquinteros** [comment]
@Dexus Awesome! 

I'll start a new release roadmap so after we finish all new changes we rollout a new release version number.
