### ISSUE TITLE
Add support for localized content like images and other stuff "Getdata"

### ISSUE THREAD

**Issue by Dexus** [leonelquinteros/gotext#20]
# Please describe your issue

## Is this a bug, an improvement, a proposal or something else? 

- [X] Improvement
- [X] Proposal

Sometimes I have to deliver pictures or PDFs related to localization, so it would be a very good idea to save this data as "LC_RESSOURCES" and deliver it with the module.

**Comment by leonelquinteros** [comment]
I think this is a very personal approach and it's outside the scope of the package. 

Others may want to use a different directories structure, or store these in a DB, or in a Cloud storage service, or anywhere else, not mentioning that they may also have different rules about how these resources are managed. 

In your case, you can use gettext translations to translate file paths as strings and then consume from the path "translated". But that's just a suggestion.
