### ISSUE TITLE
Doesn't translate to Arabic

### ISSUE THREAD

**Issue by toby3d** [leonelquinteros/gotext#25]
The package can not work with Arabic translations:

My `ar/categories.po` translation:
```gotext
...
msgid "Alcohol & Tobacco"
msgstr "الكحول والتبغ"
...
```

Go example:
```go
locale := gotext.NewLocale("i18n/", "ar")
locale.AddDomain("categories")
log.Println(locale.GetD("categories", "Alcohol & Tobacco", nil))
```

Output:
```bash
2018/08/14 17:33:18 %!(EXTRA <nil>)
```

**Comment by leonelquinteros** [comment]
@toby3d The `%!(EXTRA <nil>)` message you're receiving is because you're passing a `nil` parameter to the `GetD` method, for a string that doesn't expect to receive any parameter.

You should be getting the arabic translation for that anyway, so I'm writing a test for this case to see what's happening.

**Comment by leonelquinteros** [comment]
@toby3d Please see last commit. I've copied your code into a test and it looks good from my side. 

Maybe the path you're using for the `gotext.NewLocale` method isn't correct. Or maybe you have a syntax error in the .po file prior to the `"Alcohol & Tobacco"` translation definition. 

I'm leaving this issue open so I can provide some support for you, but please check the code on your side to figure out what's wrong.

**Comment by toby3d** [comment]
@leonelquinteros Okay, thanks, I'll check it deeper in the next day or two and let you know.

**Comment by toby3d** [comment]
I apologize for the long answer:
testing showed that the translation works correctly for all languages, except for languages from the right-left. Maybe the problem is really in .po files, but I'm not sure.

I will re-open the issue if I can reproduce the bug more in detail.
