### ISSUE TITLE
some country not have Plural form

### ISSUE THREAD

**Issue by hanjk1234** [leonelquinteros/gotext#32]
for example
en_US heads
`"Plural-Forms: nplurals=2; plural=(n != 1);\n"`

ru_RU head
`"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
`
but  zh_CN  heads  not Support
`"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"`

panic error:
`panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 6 [running]:
testing.tRunner.func1(0xc4200ce0f0)
	/usr/local/Cellar/go/1.9.2/src/testing/testing.go:711 +0x2d2
panic(0x11473a0, 0x123aad0)
	/usr/local/Cellar/go/1.9.2/src/runtime/panic.go:491 +0x283
git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals.tokenize(0x0, 0x0, 0xc420055990, 0x10, 0x10)
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals/compiler.go:362 +0x529
git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals.compileTest(0x0, 0x0, 0x4, 0x0, 0x0, 0x0)
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals/compiler.go:414 +0x4d
git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals.ternaryStruct.compile(0xc420010c80, 0x4, 0x4, 0x1173781, 0x1, 0xc420055a01, 0x2)
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals/compiler.go:42 +0x147
git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals.compileExpression(0xc420014a50, 0xe, 0xa, 0x1173987, 0x4, 0xc420014a50)
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals/compiler.go:407 +0xaa
git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals.Compile(0xc420016ca9, 0xa, 0xc420016ca2, 0x6, 0x2, 0xc42000d8c0)
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/plurals/compiler.go:390 +0x85
git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext.(*Po).parseHeaders(0xc42009e1b0)
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/po.go:350 +0x509
git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext.(*Po).Parse(0xc42009e1b0, 0xc4200c4a80, 0x728, 0x928)
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/po.go:178 +0x676
git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext.(*Po).ParseFile(0xc42009e1b0, 0xc420016ab0, 0x22)
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/po.go:105 +0xb8
git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext.(*Locale).AddDomain(0xc4200808c0, 0xc4200163d9, 0x8)
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/internal/gotext/locale.go:108 +0xb8
git.xiaojukeji.com/soda-framework/go-polyglot.Init.func1()
	/Users/zava/golang/src/git.xiaojukeji.com/soda-framework/go-polyglot/gettext.go:65 +0x18b`

**Comment by leonelquinteros** [comment]
If you have this line `"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"` in your .po file, that's probably what's failing. 

`INTEGER` and `EXPRESSION` aren't valid values for these Plural-Forms header. 

You can try removing the `Plural-Forms` line, or change these values to valid expressions like: 

`"Plural-Forms: nplurals=1; plural=0;"`

You can check the gettext docs for examples on Plural-Forms expressions. 

Let me know if that solves your issue.

**Comment by hanjk1234** [comment]
thanks!!
