### ISSUE TITLE
gotext cli tool should mimic xgettext cli

### ISSUE THREAD

**Issue by Pixdigit** [leonelquinteros/gotext#38]
I know there is a lot to implement if one wants to copy the complete xgettext cli but I would at least implement the behaviour with reading in files. I.e. that the last argument is a filelist to be read in. I already made a fork and would implement that there.
This would allow a tool like poedit to automatically extract strings from code.

**Comment by leonelquinteros** [comment]
Thank you @Pixdigit 
I think it's a good idea, I'vec assigned you this issue as you mentioned you'll work on an initial implementation for this. 

I'll look forward for your PR.

**Comment by Pixdigit** [comment]
Sorry for the late reply but I sadly don't find the time to implement this myself.
