### ISSUE TITLE
Translating HTML templates

### ISSUE THREAD

**Issue by megamayoy** [leonelquinteros/gotext#48]
# Please describe your issue
I have a small HTML template that have a small message sent via email

the HTML template contains dynamic variables as follows 
`<p> Following up on your proposal on {{.ApplicationDate}} </p>`

Can you guide me on how to generate translation messages for HTML templates?

**Comment by leonelquinteros** [comment]
Hi @megamayoy, not sure which part you need help with. 
To generate translation messages, you can either edit a Po file by hand or use any gettext utilities to create it. 

From there, you can follow up the docs in the README file on this repo, to get everything working. 

And then, when you have a Locale object loaded with your translation messages, you can pass it up as a variable to your template renderer, probably using https://golang.org/pkg/html/template/#Template.Execute to be used as a function call to translate your messages, as follows: 

If you set a `Loc` variable to your template, like: 

```go
vars := map[string]interface{}
vars["Loc"] = myLocaleObject
tpl.Execute(ioWriter, vars)
```

You can then translate any string in your template like: 
```
{{ .Loc.Get "Translate this" }}
```

Does that help?

**Comment by megamayoy** [comment]
Thank you so much.
