### ISSUE TITLE
Can't install xgotext CLI tool

### ISSUE THREAD

**Issue by megamayoy** [leonelquinteros/gotext#49]
I installed gotext successfully but Every time I try to install xgotext CLI by running 
`go install github.com/leonelquinteros/gotext/cli/xgotext`

I get this message 

> `can't load package: package github.com/leonelquinteros/gotext/cli/xgotext: module github.com/leonelquinteros/gotext@latest found (v1.4.0), but does not contain package github.com/leonelquinteros/gotext/cli/xgotext`

I try to run the command **xgotext** from the terminal but it tells me `command not found`

my go version is 
`go version go1.14.10 linux/386`

**Comment by leonelquinteros** [comment]
I think Go Modules is resolving to the latest Gotext stable version (v1.4.0) which doesn't have the xgotext package. 
You should `go get github.com/leonelquinteros/gotext@master` or something like that.
