### ISSUE TITLE
Remove external packages dependency

### ISSUE THREAD

**Issue by leonelquinteros** [leonelquinteros/gotext#5]
Implement Plural-Forms formula parser locally so we can remove Anko dependency

**Comment by mattn** [comment]
related on https://github.com/leonelquinteros/gotext/pull/7 ?

**Comment by leonelquinteros** [comment]
@mattn Yes and thanks again.
Still want to remove any dependencies from the package, but you've improved it so much already!

**Comment by Dexus** [comment]
Now we can remove it with #16.

Cheers :)

**Comment by mattn** [comment]
Congrats :)

**Comment by leonelquinteros** [comment]
Thanks all!
