### ISSUE TITLE
plurals subpackage appears to plagiarise github.com/ojii/gettext.go/pluralforms

### ISSUE THREAD

**Issue by jhenstridge** [leonelquinteros/gotext#50]
The code in plurals package includes the following copyright header:

```
/*
 * Copyright (c) 2018 DeineAgentur UG https://www.deineagentur.com. All rights reserved.
 * Licensed under the MIT License. See LICENSE file in the project root for full license information.
 */
```

However, the code appears almost identical to that found in [github.com/ojii/gettext.go/pluralforms](https://github.com/ojii/gettext.go/tree/master/pluralforms), with some types, functions, and variables renamed.  The code in the other repository was committed in 2016, so clearly predates this repo's copy.

The original code is released under the 3 clause BSD license, so reusing it should be fine provided it is correctly attributed and a copy of the original license text is included along side.

**Comment by leonelquinteros** [comment]
Hi @jhenstridge , 

Thanks for noting that out. 
This is the PR that introduced that change: https://github.com/leonelquinteros/gotext/pull/16
I really don't care who wrote the code, but understand the issue. 
@Dexus, as you're claiming rights for that code in the file, would you like to answer @jhenstridge comment about Licensing? 

I'll open some time window now to discuss this issue, let's try to get all parties involved. Not sure if @jhenstridge is the original author or just found this code match. 

On any case, I think the resolution will be a PR with the corresponding copyright text changed after all parties agree on the content of that text and License.

**Comment by Dexus** [comment]
I don't know from where I got inspired. But yes it may come from there.

I can't remember.

**Comment by jhenstridge** [comment]
I am not the original author: the code appears to be solely authored by Jonas Obrist:

https://github.com/ojii/gettext.go/commits/master/pluralforms

As I said, there's likely nothing wrong with reusing the code if it the copyright notice and license are preserved: the 3-clause BSD licensed code should be usable by pretty much any project where MIT licensed code was acceptable.
