### ISSUE TITLE
Please add cli/xgotext to v1.4.1

### ISSUE THREAD

**Issue by Antonboom** [leonelquinteros/gotext#51]
Hello!

We want to install the tool from the vendor directory, but we cannot install the `cli/xgotext`, since it is not included in the module source code:

https://github.com/leonelquinteros/gotext/tree/v1.4.0

**Comment by leonelquinteros** [comment]
Hi @Antonboom 
At this moment, `xgotext` is only available in `master` branch. You should use that branch until it gets into a stable state to be released.

**Comment by Antonboom** [comment]
@leonelquinteros, ok, thanks!

**Comment by leonelquinteros** [comment]
`xgotext` has been included in `v1.5.0` release.
