### ISSUE TITLE
expose lang from Locale

### ISSUE THREAD

**Issue by taozhou-glean** [leonelquinteros/gotext#75]
# Please describe your issue

### Is this a bug, an improvement, a proposal or something else? Describe it.

a proposal to expose `lang` from Locale.

### What's the expected behaviour, the current behaviour and the steps to reproduce it?

We load all Locale for all supported languages and store them in a global context during server start time, and do the map look up during run time. Now we have to store the `lang` altogether with the Locale so we can know what language it is, which is a bit inconvenient as the info is available to Locale already.

So an `GetLanguage` on Locale would be ideal.

### Comments

I will be happy to make the PR if this is accepted.

**Comment by leonelquinteros** [comment]
I can accept a new `Locale.GetLanguage()` method, but can't add that method to the `Translator` interface. If that works for you, I'll be happy to accept your PR. 
Otherwise, I'd say better to handle it outside the package.

**Comment by taozhou-glean** [comment]
`Locale.GetLanguage` is all I need, just feel like a bit waste to keep the same info if it is already in the Locale ;) will send you a PR soon
