### ISSUE TITLE
can we have pseudo locale support ?

### ISSUE THREAD

**Issue by taozhou-glean** [leonelquinteros/gotext#76]
# Please describe your issue

### Is this a bug, an improvement, a proposal or something else? Describe it.

proposal 

### What's the expected behaviour, the current behaviour and the steps to reproduce it?

We have pseudo support in FE, and would be great if we have that for Go from the library directly, it can be simple as char randomization (for english or alphabet languages, it can be just normal char to accented chars)

**Comment by leonelquinteros** [comment]
Hi, not sure I'm following the proposal, could you describe it further?

**Comment by taozhou-glean** [comment]
ah we use https://en.wikipedia.org/wiki/Pseudolocalization during development to get a sense of i18n coverage without waiting for the actual translation (as we are in an incremental migration), right now I have to duplicate the english message file (our source language) and manually pseudo them for every new messages, while our FE i18n library will do the pseudolocalization for us, so I just thought it would be convenient if the gotext can provide such functionality out of box ;) (if I am not asking too much)

**Comment by leonelquinteros** [comment]
Are we talking about language file (.po) generation? Or the package returning random chars for every `Get`?

**Comment by taozhou-glean** [comment]
either way we can achieve the same result, the pseudo can be done either in the po generation time or runtime (`Get`), but it seems the xgotext only supports `.pot` and not per locale, so I guess you would prefer po generation to be done manually instead.

**Comment by leonelquinteros** [comment]
Exactly, it's just a tool that takes a language file and generates another by filling the values. This one belongs to a different package/tool.
