### ISSUE TITLE
Remove plural default in Po Gets

### ISSUE THREAD

**Issue by segeschecho** [leonelquinteros/gotext#8]
Return singular or plural (by checking N) instead of plural form by default.

GetN and GetNC functions both have plural and singular strings available and the "n" to determine which one to return.

It doesn't seem natural to expect a default plural string when it wasn't possible to translate the string.

**Comment by leonelquinteros** [comment]
@segeschecho Thanks for the report! 

It also matches the behaviour of the original `ngettext` as described in the docs: https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

> ... If no message catalog is found msgid1 is returned if n == 1, otherwise msgid2.

I've pushed a fix for it and make it a release soon.

**Comment by segeschecho** [comment]
@leonelquinteros Thank you !
