### ISSUE TITLE
Properly tag the latest release

### ISSUE THREAD

**Issue by donseba** [leonelquinteros/gotext#91]
# Please describe your issue
importing `github.com/leonelquinteros/gotext` does not contain the methods to check if a key is translated i.e. `IsTranslated`  

I'd like to request you to tag the latest state as `v1.5.3` 

importing the repo as `github.com/leonelquinteros/gotext v1.5.3-0.20231003122255-12a99145a351` solved my issue for now.

**Comment by leonelquinteros** [comment]
Created new v1.6.0 tag with latest changes in the code.
