### ISSUE TITLE
Active repository moved

### ISSUE THREAD

**Issue by donseba** [leonelquinteros/gotext#94]
Hey everyone! 🎉

I've kinda taken the reins on maintaining this branch of gotext over at https://github.com/donseba/gotext. I’ve been tidying up a few things, squashing bugs, and I'm totally open to any cool ideas you've got for new features. So, don't be shy; hit me up with those PRs!

I've also noticed that the code’s style is a bit all over the place. Thinking it might be time for a little makeover or even a full-on rewrite to keep things smooth and consistent. What do you think?

If you’ve been using gotext, want to contribute, or have some thoughts on the direction we should take, let's chat. Whether it's improving what's already there or brainstorming brand new features, your input is super welcome.

Let’s make gotext awesome together! 🚀

**Comment by gedw99** [comment]
On your repo Issues returned off .

**Comment by donseba** [comment]
Ive no clue what your trying to say.

**Comment by donseba** [comment]
> On your repo Issues returned off .

oh i see now, ive enabled it .

**Comment by gedw99** [comment]
Ok thanks 🙏
