### ISSUE TITLE
Implemented a few improvements

### ISSUE THREAD

**Issue by sblinch** [leonelquinteros/gotext#96]
I've implemented a few improvements to gotext for my own use and thought I'd offer them back.

The first is [a set of "Append"](https://github.com/leonelquinteros/gotext/commit/8cc53ef798ad9e4ad1caed79efc704aff1fcd695) equivalents to the Get[NC] methods that append to a byte slice instead of allocating new strings. This improves performance substantially:

```
BenchmarkGoText/strings-16                748399              1627 ns/op             160 B/op          6 allocs/op
BenchmarkGoText/byte-slices-16           1044115              1094 ns/op              48 B/op          3 allocs/op
```

I also have a patch that replaces gotext's maps/mutexes with [lock-free hashmaps](https://github.com/cornelk/hashmap). The performance improvement wasn't as dramatic as I had hoped, and it requires an additional dependency (hashmap) and bumping the required Go version to 1.18 for generics support, so I'm not sure it'll meet the bar for inclusion in gotext. Performance (vs the above):

```
BenchmarkGoTextHashmaps/strings-16          915142              1342 ns/op             160 B/op          6 allocs/op
BenchmarkGoTextHashmaps/byte-slices-16     1195036               893.6 ns/op            48 B/op          3 allocs/op
```

If there's any interest, I can rebase it on top of the current version and push it to my repo for review.

**Comment by leonelquinteros** [comment]
Thank you very much for your contributions. And sorry for the late response here. 
I've merged a PR containing the new Append functions. 
I don't feel there is a need for performance optimization at this moment, so I wouldn't add a dependency just for that now. 

Thanks again!
